dictionaries = [
    "en_gb",
    "en_us",
]
words = [
    "balancer",
    "codebook",
    "docker's",
    "ecs",
    "homebrew",
    "iam",
    "mise",
    "nginx",
    "npmrc",
    "npx",
    "pdfviewer",
    "postgre",
    "tfenv",
    "tflint",
    "userprofile",
    "vscode",
    "waf",
]
ignore_patterns = [
    '\b[ATCG]+\b',
    '\d{3}-\d{2}-\d{4}',
    "^[A-Z]{2,}$",
    'https?://[^\s]+',
]
