theme = "monokai_pro_spectrum"

[editor]
end-of-line-diagnostics = "hint"
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.lsp]
display-inlay-hints = true
