local utils = require('languages._utils')
return {
  on_attach = utils.on_attach,
  cmd = { 'codebook-lsp', 'serve' },
  filetypes = {
    'c',
    'css',
    'gitcommit',
    'go',
    'haskell',
    'html',
    'java',
    'javascript',
    'javascriptreact',
    'lua',
    'markdown',
    'php',
    'python',
    'ruby',
    'rust',
    'toml',
    'text',
    'typescript',
    'typescriptreact',
  },
  root_markers = { 'codebook.toml', '.codebook.toml', '.git' },
}
